// International dialing codes for every country/territory in the world.
// Used by the Phone Number field to pick a country calling code (lada).
// `code3` is the ISO 3166-1 alpha-3 code shown in the dropdown.
export interface CountryCode {
  name: string
  iso: string
  code3: string
  dial: string
}

// Converts a 2-letter ISO country code into its flag emoji by mapping each
// letter to its Regional Indicator Symbol. Rendering depends on OS emoji
// support, but works on macOS/iOS and most modern platforms.
export function flagEmoji(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/[A-Z]/g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
}

const RAW_COUNTRIES: CountryCode[] = [
  { name: 'Afghanistan', iso: 'AF', code3: 'AFG', dial: '+93' },
  { name: 'Albania', iso: 'AL', code3: 'ALB', dial: '+355' },
  { name: 'Algeria', iso: 'DZ', code3: 'DZA', dial: '+213' },
  { name: 'American Samoa', iso: 'AS', code3: 'ASM', dial: '+1684' },
  { name: 'Andorra', iso: 'AD', code3: 'AND', dial: '+376' },
  { name: 'Angola', iso: 'AO', code3: 'AGO', dial: '+244' },
  { name: 'Anguilla', iso: 'AI', code3: 'AIA', dial: '+1264' },
  { name: 'Antigua and Barbuda', iso: 'AG', code3: 'ATG', dial: '+1268' },
  { name: 'Argentina', iso: 'AR', code3: 'ARG', dial: '+54' },
  { name: 'Armenia', iso: 'AM', code3: 'ARM', dial: '+374' },
  { name: 'Aruba', iso: 'AW', code3: 'ABW', dial: '+297' },
  { name: 'Australia', iso: 'AU', code3: 'AUS', dial: '+61' },
  { name: 'Austria', iso: 'AT', code3: 'AUT', dial: '+43' },
  { name: 'Azerbaijan', iso: 'AZ', code3: 'AZE', dial: '+994' },
  { name: 'Bahamas', iso: 'BS', code3: 'BHS', dial: '+1242' },
  { name: 'Bahrain', iso: 'BH', code3: 'BHR', dial: '+973' },
  { name: 'Bangladesh', iso: 'BD', code3: 'BGD', dial: '+880' },
  { name: 'Barbados', iso: 'BB', code3: 'BRB', dial: '+1246' },
  { name: 'Belarus', iso: 'BY', code3: 'BLR', dial: '+375' },
  { name: 'Belgium', iso: 'BE', code3: 'BEL', dial: '+32' },
  { name: 'Belize', iso: 'BZ', code3: 'BLZ', dial: '+501' },
  { name: 'Benin', iso: 'BJ', code3: 'BEN', dial: '+229' },
  { name: 'Bermuda', iso: 'BM', code3: 'BMU', dial: '+1441' },
  { name: 'Bhutan', iso: 'BT', code3: 'BTN', dial: '+975' },
  { name: 'Bolivia', iso: 'BO', code3: 'BOL', dial: '+591' },
  { name: 'Bosnia and Herzegovina', iso: 'BA', code3: 'BIH', dial: '+387' },
  { name: 'Botswana', iso: 'BW', code3: 'BWA', dial: '+267' },
  { name: 'Brazil', iso: 'BR', code3: 'BRA', dial: '+55' },
  { name: 'British Indian Ocean Territory', iso: 'IO', code3: 'IOT', dial: '+246' },
  { name: 'British Virgin Islands', iso: 'VG', code3: 'VGB', dial: '+1284' },
  { name: 'Brunei', iso: 'BN', code3: 'BRN', dial: '+673' },
  { name: 'Bulgaria', iso: 'BG', code3: 'BGR', dial: '+359' },
  { name: 'Burkina Faso', iso: 'BF', code3: 'BFA', dial: '+226' },
  { name: 'Burundi', iso: 'BI', code3: 'BDI', dial: '+257' },
  { name: 'Cambodia', iso: 'KH', code3: 'KHM', dial: '+855' },
  { name: 'Cameroon', iso: 'CM', code3: 'CMR', dial: '+237' },
  { name: 'Canada', iso: 'CA', code3: 'CAN', dial: '+1' },
  { name: 'Cape Verde', iso: 'CV', code3: 'CPV', dial: '+238' },
  { name: 'Cayman Islands', iso: 'KY', code3: 'CYM', dial: '+1345' },
  { name: 'Central African Republic', iso: 'CF', code3: 'CAF', dial: '+236' },
  { name: 'Chad', iso: 'TD', code3: 'TCD', dial: '+235' },
  { name: 'Chile', iso: 'CL', code3: 'CHL', dial: '+56' },
  { name: 'China', iso: 'CN', code3: 'CHN', dial: '+86' },
  { name: 'Christmas Island', iso: 'CX', code3: 'CXR', dial: '+61' },
  { name: 'Cocos (Keeling) Islands', iso: 'CC', code3: 'CCK', dial: '+61' },
  { name: 'Colombia', iso: 'CO', code3: 'COL', dial: '+57' },
  { name: 'Comoros', iso: 'KM', code3: 'COM', dial: '+269' },
  { name: 'Congo (Brazzaville)', iso: 'CG', code3: 'COG', dial: '+242' },
  { name: 'Congo (Kinshasa)', iso: 'CD', code3: 'COD', dial: '+243' },
  { name: 'Cook Islands', iso: 'CK', code3: 'COK', dial: '+682' },
  { name: 'Costa Rica', iso: 'CR', code3: 'CRI', dial: '+506' },
  { name: "Côte d'Ivoire", iso: 'CI', code3: 'CIV', dial: '+225' },
  { name: 'Croatia', iso: 'HR', code3: 'HRV', dial: '+385' },
  { name: 'Cuba', iso: 'CU', code3: 'CUB', dial: '+53' },
  { name: 'Curaçao', iso: 'CW', code3: 'CUW', dial: '+599' },
  { name: 'Cyprus', iso: 'CY', code3: 'CYP', dial: '+357' },
  { name: 'Czech Republic', iso: 'CZ', code3: 'CZE', dial: '+420' },
  { name: 'Denmark', iso: 'DK', code3: 'DNK', dial: '+45' },
  { name: 'Djibouti', iso: 'DJ', code3: 'DJI', dial: '+253' },
  { name: 'Dominica', iso: 'DM', code3: 'DMA', dial: '+1767' },
  { name: 'Dominican Republic', iso: 'DO', code3: 'DOM', dial: '+1809' },
  { name: 'Ecuador', iso: 'EC', code3: 'ECU', dial: '+593' },
  { name: 'Egypt', iso: 'EG', code3: 'EGY', dial: '+20' },
  { name: 'El Salvador', iso: 'SV', code3: 'SLV', dial: '+503' },
  { name: 'Equatorial Guinea', iso: 'GQ', code3: 'GNQ', dial: '+240' },
  { name: 'Eritrea', iso: 'ER', code3: 'ERI', dial: '+291' },
  { name: 'Estonia', iso: 'EE', code3: 'EST', dial: '+372' },
  { name: 'Eswatini', iso: 'SZ', code3: 'SWZ', dial: '+268' },
  { name: 'Ethiopia', iso: 'ET', code3: 'ETH', dial: '+251' },
  { name: 'Falkland Islands', iso: 'FK', code3: 'FLK', dial: '+500' },
  { name: 'Faroe Islands', iso: 'FO', code3: 'FRO', dial: '+298' },
  { name: 'Fiji', iso: 'FJ', code3: 'FJI', dial: '+679' },
  { name: 'Finland', iso: 'FI', code3: 'FIN', dial: '+358' },
  { name: 'France', iso: 'FR', code3: 'FRA', dial: '+33' },
  { name: 'French Guiana', iso: 'GF', code3: 'GUF', dial: '+594' },
  { name: 'French Polynesia', iso: 'PF', code3: 'PYF', dial: '+689' },
  { name: 'Gabon', iso: 'GA', code3: 'GAB', dial: '+241' },
  { name: 'Gambia', iso: 'GM', code3: 'GMB', dial: '+220' },
  { name: 'Georgia', iso: 'GE', code3: 'GEO', dial: '+995' },
  { name: 'Germany', iso: 'DE', code3: 'DEU', dial: '+49' },
  { name: 'Ghana', iso: 'GH', code3: 'GHA', dial: '+233' },
  { name: 'Gibraltar', iso: 'GI', code3: 'GIB', dial: '+350' },
  { name: 'Greece', iso: 'GR', code3: 'GRC', dial: '+30' },
  { name: 'Greenland', iso: 'GL', code3: 'GRL', dial: '+299' },
  { name: 'Grenada', iso: 'GD', code3: 'GRD', dial: '+1473' },
  { name: 'Guadeloupe', iso: 'GP', code3: 'GLP', dial: '+590' },
  { name: 'Guam', iso: 'GU', code3: 'GUM', dial: '+1671' },
  { name: 'Guatemala', iso: 'GT', code3: 'GTM', dial: '+502' },
  { name: 'Guernsey', iso: 'GG', code3: 'GGY', dial: '+44' },
  { name: 'Guinea', iso: 'GN', code3: 'GIN', dial: '+224' },
  { name: 'Guinea-Bissau', iso: 'GW', code3: 'GNB', dial: '+245' },
  { name: 'Guyana', iso: 'GY', code3: 'GUY', dial: '+592' },
  { name: 'Haiti', iso: 'HT', code3: 'HTI', dial: '+509' },
  { name: 'Honduras', iso: 'HN', code3: 'HND', dial: '+504' },
  { name: 'Hong Kong', iso: 'HK', code3: 'HKG', dial: '+852' },
  { name: 'Hungary', iso: 'HU', code3: 'HUN', dial: '+36' },
  { name: 'Iceland', iso: 'IS', code3: 'ISL', dial: '+354' },
  { name: 'India', iso: 'IN', code3: 'IND', dial: '+91' },
  { name: 'Indonesia', iso: 'ID', code3: 'IDN', dial: '+62' },
  { name: 'Iran', iso: 'IR', code3: 'IRN', dial: '+98' },
  { name: 'Iraq', iso: 'IQ', code3: 'IRQ', dial: '+964' },
  { name: 'Ireland', iso: 'IE', code3: 'IRL', dial: '+353' },
  { name: 'Isle of Man', iso: 'IM', code3: 'IMN', dial: '+44' },
  { name: 'Israel', iso: 'IL', code3: 'ISR', dial: '+972' },
  { name: 'Italy', iso: 'IT', code3: 'ITA', dial: '+39' },
  { name: 'Jamaica', iso: 'JM', code3: 'JAM', dial: '+1876' },
  { name: 'Japan', iso: 'JP', code3: 'JPN', dial: '+81' },
  { name: 'Jersey', iso: 'JE', code3: 'JEY', dial: '+44' },
  { name: 'Jordan', iso: 'JO', code3: 'JOR', dial: '+962' },
  { name: 'Kazakhstan', iso: 'KZ', code3: 'KAZ', dial: '+7' },
  { name: 'Kenya', iso: 'KE', code3: 'KEN', dial: '+254' },
  { name: 'Kiribati', iso: 'KI', code3: 'KIR', dial: '+686' },
  { name: 'Kosovo', iso: 'XK', code3: 'XKX', dial: '+383' },
  { name: 'Kuwait', iso: 'KW', code3: 'KWT', dial: '+965' },
  { name: 'Kyrgyzstan', iso: 'KG', code3: 'KGZ', dial: '+996' },
  { name: 'Laos', iso: 'LA', code3: 'LAO', dial: '+856' },
  { name: 'Latvia', iso: 'LV', code3: 'LVA', dial: '+371' },
  { name: 'Lebanon', iso: 'LB', code3: 'LBN', dial: '+961' },
  { name: 'Lesotho', iso: 'LS', code3: 'LSO', dial: '+266' },
  { name: 'Liberia', iso: 'LR', code3: 'LBR', dial: '+231' },
  { name: 'Libya', iso: 'LY', code3: 'LBY', dial: '+218' },
  { name: 'Liechtenstein', iso: 'LI', code3: 'LIE', dial: '+423' },
  { name: 'Lithuania', iso: 'LT', code3: 'LTU', dial: '+370' },
  { name: 'Luxembourg', iso: 'LU', code3: 'LUX', dial: '+352' },
  { name: 'Macau', iso: 'MO', code3: 'MAC', dial: '+853' },
  { name: 'Madagascar', iso: 'MG', code3: 'MDG', dial: '+261' },
  { name: 'Malawi', iso: 'MW', code3: 'MWI', dial: '+265' },
  { name: 'Malaysia', iso: 'MY', code3: 'MYS', dial: '+60' },
  { name: 'Maldives', iso: 'MV', code3: 'MDV', dial: '+960' },
  { name: 'Mali', iso: 'ML', code3: 'MLI', dial: '+223' },
  { name: 'Malta', iso: 'MT', code3: 'MLT', dial: '+356' },
  { name: 'Marshall Islands', iso: 'MH', code3: 'MHL', dial: '+692' },
  { name: 'Martinique', iso: 'MQ', code3: 'MTQ', dial: '+596' },
  { name: 'Mauritania', iso: 'MR', code3: 'MRT', dial: '+222' },
  { name: 'Mauritius', iso: 'MU', code3: 'MUS', dial: '+230' },
  { name: 'Mayotte', iso: 'YT', code3: 'MYT', dial: '+262' },
  { name: 'Mexico', iso: 'MX', code3: 'MEX', dial: '+52' },
  { name: 'Micronesia', iso: 'FM', code3: 'FSM', dial: '+691' },
  { name: 'Moldova', iso: 'MD', code3: 'MDA', dial: '+373' },
  { name: 'Monaco', iso: 'MC', code3: 'MCO', dial: '+377' },
  { name: 'Mongolia', iso: 'MN', code3: 'MNG', dial: '+976' },
  { name: 'Montenegro', iso: 'ME', code3: 'MNE', dial: '+382' },
  { name: 'Montserrat', iso: 'MS', code3: 'MSR', dial: '+1664' },
  { name: 'Morocco', iso: 'MA', code3: 'MAR', dial: '+212' },
  { name: 'Mozambique', iso: 'MZ', code3: 'MOZ', dial: '+258' },
  { name: 'Myanmar', iso: 'MM', code3: 'MMR', dial: '+95' },
  { name: 'Namibia', iso: 'NA', code3: 'NAM', dial: '+264' },
  { name: 'Nauru', iso: 'NR', code3: 'NRU', dial: '+674' },
  { name: 'Nepal', iso: 'NP', code3: 'NPL', dial: '+977' },
  { name: 'Netherlands', iso: 'NL', code3: 'NLD', dial: '+31' },
  { name: 'New Caledonia', iso: 'NC', code3: 'NCL', dial: '+687' },
  { name: 'New Zealand', iso: 'NZ', code3: 'NZL', dial: '+64' },
  { name: 'Nicaragua', iso: 'NI', code3: 'NIC', dial: '+505' },
  { name: 'Niger', iso: 'NE', code3: 'NER', dial: '+227' },
  { name: 'Nigeria', iso: 'NG', code3: 'NGA', dial: '+234' },
  { name: 'Niue', iso: 'NU', code3: 'NIU', dial: '+683' },
  { name: 'Norfolk Island', iso: 'NF', code3: 'NFK', dial: '+672' },
  { name: 'North Korea', iso: 'KP', code3: 'PRK', dial: '+850' },
  { name: 'North Macedonia', iso: 'MK', code3: 'MKD', dial: '+389' },
  { name: 'Northern Mariana Islands', iso: 'MP', code3: 'MNP', dial: '+1670' },
  { name: 'Norway', iso: 'NO', code3: 'NOR', dial: '+47' },
  { name: 'Oman', iso: 'OM', code3: 'OMN', dial: '+968' },
  { name: 'Pakistan', iso: 'PK', code3: 'PAK', dial: '+92' },
  { name: 'Palau', iso: 'PW', code3: 'PLW', dial: '+680' },
  { name: 'Palestine', iso: 'PS', code3: 'PSE', dial: '+970' },
  { name: 'Panama', iso: 'PA', code3: 'PAN', dial: '+507' },
  { name: 'Papua New Guinea', iso: 'PG', code3: 'PNG', dial: '+675' },
  { name: 'Paraguay', iso: 'PY', code3: 'PRY', dial: '+595' },
  { name: 'Peru', iso: 'PE', code3: 'PER', dial: '+51' },
  { name: 'Philippines', iso: 'PH', code3: 'PHL', dial: '+63' },
  { name: 'Poland', iso: 'PL', code3: 'POL', dial: '+48' },
  { name: 'Portugal', iso: 'PT', code3: 'PRT', dial: '+351' },
  { name: 'Puerto Rico', iso: 'PR', code3: 'PRI', dial: '+1787' },
  { name: 'Qatar', iso: 'QA', code3: 'QAT', dial: '+974' },
  { name: 'Réunion', iso: 'RE', code3: 'REU', dial: '+262' },
  { name: 'Romania', iso: 'RO', code3: 'ROU', dial: '+40' },
  { name: 'Russia', iso: 'RU', code3: 'RUS', dial: '+7' },
  { name: 'Rwanda', iso: 'RW', code3: 'RWA', dial: '+250' },
  { name: 'Saint Barthélemy', iso: 'BL', code3: 'BLM', dial: '+590' },
  { name: 'Saint Helena', iso: 'SH', code3: 'SHN', dial: '+290' },
  { name: 'Saint Kitts and Nevis', iso: 'KN', code3: 'KNA', dial: '+1869' },
  { name: 'Saint Lucia', iso: 'LC', code3: 'LCA', dial: '+1758' },
  { name: 'Saint Martin', iso: 'MF', code3: 'MAF', dial: '+590' },
  { name: 'Saint Pierre and Miquelon', iso: 'PM', code3: 'SPM', dial: '+508' },
  { name: 'Saint Vincent and the Grenadines', iso: 'VC', code3: 'VCT', dial: '+1784' },
  { name: 'Samoa', iso: 'WS', code3: 'WSM', dial: '+685' },
  { name: 'San Marino', iso: 'SM', code3: 'SMR', dial: '+378' },
  { name: 'São Tomé and Príncipe', iso: 'ST', code3: 'STP', dial: '+239' },
  { name: 'Saudi Arabia', iso: 'SA', code3: 'SAU', dial: '+966' },
  { name: 'Senegal', iso: 'SN', code3: 'SEN', dial: '+221' },
  { name: 'Serbia', iso: 'RS', code3: 'SRB', dial: '+381' },
  { name: 'Seychelles', iso: 'SC', code3: 'SYC', dial: '+248' },
  { name: 'Sierra Leone', iso: 'SL', code3: 'SLE', dial: '+232' },
  { name: 'Singapore', iso: 'SG', code3: 'SGP', dial: '+65' },
  { name: 'Sint Maarten', iso: 'SX', code3: 'SXM', dial: '+1721' },
  { name: 'Slovakia', iso: 'SK', code3: 'SVK', dial: '+421' },
  { name: 'Slovenia', iso: 'SI', code3: 'SVN', dial: '+386' },
  { name: 'Solomon Islands', iso: 'SB', code3: 'SLB', dial: '+677' },
  { name: 'Somalia', iso: 'SO', code3: 'SOM', dial: '+252' },
  { name: 'South Africa', iso: 'ZA', code3: 'ZAF', dial: '+27' },
  { name: 'South Korea', iso: 'KR', code3: 'KOR', dial: '+82' },
  { name: 'South Sudan', iso: 'SS', code3: 'SSD', dial: '+211' },
  { name: 'Spain', iso: 'ES', code3: 'ESP', dial: '+34' },
  { name: 'Sri Lanka', iso: 'LK', code3: 'LKA', dial: '+94' },
  { name: 'Sudan', iso: 'SD', code3: 'SDN', dial: '+249' },
  { name: 'Suriname', iso: 'SR', code3: 'SUR', dial: '+597' },
  { name: 'Sweden', iso: 'SE', code3: 'SWE', dial: '+46' },
  { name: 'Switzerland', iso: 'CH', code3: 'CHE', dial: '+41' },
  { name: 'Syria', iso: 'SY', code3: 'SYR', dial: '+963' },
  { name: 'Taiwan', iso: 'TW', code3: 'TWN', dial: '+886' },
  { name: 'Tajikistan', iso: 'TJ', code3: 'TJK', dial: '+992' },
  { name: 'Tanzania', iso: 'TZ', code3: 'TZA', dial: '+255' },
  { name: 'Thailand', iso: 'TH', code3: 'THA', dial: '+66' },
  { name: 'Timor-Leste', iso: 'TL', code3: 'TLS', dial: '+670' },
  { name: 'Togo', iso: 'TG', code3: 'TGO', dial: '+228' },
  { name: 'Tokelau', iso: 'TK', code3: 'TKL', dial: '+690' },
  { name: 'Tonga', iso: 'TO', code3: 'TON', dial: '+676' },
  { name: 'Trinidad and Tobago', iso: 'TT', code3: 'TTO', dial: '+1868' },
  { name: 'Tunisia', iso: 'TN', code3: 'TUN', dial: '+216' },
  { name: 'Turkey', iso: 'TR', code3: 'TUR', dial: '+90' },
  { name: 'Turkmenistan', iso: 'TM', code3: 'TKM', dial: '+993' },
  { name: 'Turks and Caicos Islands', iso: 'TC', code3: 'TCA', dial: '+1649' },
  { name: 'Tuvalu', iso: 'TV', code3: 'TUV', dial: '+688' },
  { name: 'Uganda', iso: 'UG', code3: 'UGA', dial: '+256' },
  { name: 'Ukraine', iso: 'UA', code3: 'UKR', dial: '+380' },
  { name: 'United Arab Emirates', iso: 'AE', code3: 'ARE', dial: '+971' },
  { name: 'United Kingdom', iso: 'GB', code3: 'GBR', dial: '+44' },
  { name: 'United States', iso: 'US', code3: 'USA', dial: '+1' },
  { name: 'Uruguay', iso: 'UY', code3: 'URY', dial: '+598' },
  { name: 'Uzbekistan', iso: 'UZ', code3: 'UZB', dial: '+998' },
  { name: 'Vanuatu', iso: 'VU', code3: 'VUT', dial: '+678' },
  { name: 'Vatican City', iso: 'VA', code3: 'VAT', dial: '+379' },
  { name: 'Venezuela', iso: 'VE', code3: 'VEN', dial: '+58' },
  { name: 'Vietnam', iso: 'VN', code3: 'VNM', dial: '+84' },
  { name: 'Wallis and Futuna', iso: 'WF', code3: 'WLF', dial: '+681' },
  { name: 'Yemen', iso: 'YE', code3: 'YEM', dial: '+967' },
  { name: 'Zambia', iso: 'ZM', code3: 'ZMB', dial: '+260' },
  { name: 'Zimbabwe', iso: 'ZW', code3: 'ZWE', dial: '+263' },
]

// These appear first, in this exact order. The rest follow alphabetically by
// their 3-letter code.
const PINNED_CODES = ['MEX', 'USA', 'CAN', 'ESP', 'COL']

const pinned = PINNED_CODES.map(
  (code) => RAW_COUNTRIES.find((country) => country.code3 === code)!,
)

const rest = RAW_COUNTRIES.filter((country) => !PINNED_CODES.includes(country.code3)).sort((a, b) =>
  a.code3.localeCompare(b.code3),
)

export const COUNTRY_CODES: CountryCode[] = [...pinned, ...rest]
